export const environment = {
  production: true,
  apiUrl: "http://192.168.100.150:8000/api/",
  alumnos: "alumnos",
  materias: "materias",
  matriculas: "matriculas",
  notas: "notas",
  unidades: "unidades",
  profesores: "profesores",
  apiUrlFirma: "http://192.168.100.150:8000/api/",
  apiUrlCuestionario: "http://192.168.100.150:8000/api/jefatura/",
  crearCuestionario: "crearCuestionario",
  contestarCuestionario: "crearCuestionarioRespondido",
  obtenerCuestionarioURL: "obtenerCuestionario",
  obtenerCuestionariosURL: "listarCuestionarios",
  eliminarCuestionarioURL: "eliminarCuestionario",
  obtenerCuestionarioEdicionURL: "obtenerCuestionarioEdicion",
  editarCuestionarioURL: "editarCuestionario",
  verificarCuestionarioRespondidoURL: "verificarCuestionarioRespondido",
  obtenerCuestionariosFCTURL: "obtenerCuestionariosFCT",
  activarCuestionarioURL: "activarCuestionario",
  desactivarCuestionarioURL: "desactivarCuestionario",
  obtenerMediasCuestionariosRespondidosURL: "obtenerMediasCuestionariosRespondidos",
  obtenerCursosAcademicosURL: "obtenerCursosAcademicos",
  listarCuestionariosRespondidosURL: "listarCuestionariosRespondidos",
  descargarCuestionarioURL: "descargarCuestionario",
};
